const pool = require('./db');

const teaching = [
    ["Teacher I", 11]
];

const schoolAdmin = [
    ["School Principal IV", 22],
    ["School Principal III", 21],
    ["Assistant School Principal III", 20],
    ["School Principal II", 20],
    ["Special School Principal II", 20],
    ["Assistant School Principal II", 19],
    ["Head Teacher VI", 19],
    ["School Principal I", 19],
    ["Special School Principal I", 19],
    ["Assistant School Principal I", 18],
    ["Assistant Special School Principal", 18],
    ["Head Teacher V", 18],
    ["Head Teacher IV", 17],
    ["Head Teacher III", 16],
    ["Head Teacher II", 15],
    ["Head Teacher I", 14]
];

const relatedTeaching = [
    ["Chief Education Program Specialist", 24],
    ["Education Program Supervisor", 22],
    ["Public Schools District Supervisor", 22],
    ["Supervising Education Program Specialist", 22],
    ["Senior Education Program Specialist", 19],
    ["Senior Science Research Specialist", 19],
    ["Vocational Instruction Supervisor III", 18],
    ["Vocational Instruction Supervisor II", 17],
    ["Education Program Specialist II", 16],
    ["Guidance Coordinator III", 16],
    ["Science Research Specialist II", 16],
    ["Science Research Technician IV", 16],
    ["Vocational Instruction Supervisor I", 16],
    ["Guidance Coordinator II", 15],
    ["School Farming Coordinator III", 15],
    ["Teacher Credentials Evaluator II", 15],
    ["Guidance Coordinator I", 14],
    ["School Farming Coordinator II", 14],
    ["Guidance Counselor III", 13],
    ["School Farming Coordinator I", 13],
    ["Science Research Technician III", 13],
    ["Teacher Credentials Evaluator I", 13],
    ["Crafts Education Demonstrator II", 12],
    ["Education Program Specialist I", 12],
    ["Guidance Counselor II", 12],
    ["Guidance Counselor I", 11],
    ["Science Research Technician II", 11],
    ["Teaching-Aids Specialist", 11],
    ["Crafts Education Demonstrator I", 10],
    ["Education Research Assistant II", 10],
    ["School Farm Demonstrator", 10]
];

const nonTeaching = [
    ["Attorney V", 25],
    ["Chief Accountant", 24],
    ["Chief Administrative Officer", 24],
    ["Chief Education Supervisor", 24],
    ["Chief Health Program Officer", 24],
    ["Engineer V", 24],
    ["Information Technology Officer III", 24],
    ["Internal Auditor V", 24],
    ["Planning Officer V", 24],
    ["Project Development Officer V", 24],
    ["Teachers' Camp Superintendent", 24],
    ["Attorney IV", 23],
    ["Medical Officer IV", 23],
    ["Vocational School Administrator II", 23],
    ["Accountant IV", 22],
    ["Assistant Teacher's Camp Superintendent", 22],
    ["Department Legislative Liaison Specialist", 22],
    ["Engineer IV", 22],
    ["Information Technology Officer II", 22],
    ["Internal Auditor IV", 22],
    ["Planning Officer IV", 22],
    ["Project Development Officer IV", 22],
    ["Project Evaluation Officer IV", 22],
    ["Security Officer IV", 22],
    ["Supervising Administrative Officer", 22],
    ["Supervising Health Program Officer", 22],
    ["Vocational School Administrator I", 22],
    ["Attorney III", 21],
    ["Medical Officer III", 21],
    ["Dentist III", 20],
    ["Accountant III", 19],
    ["Architect III", 19],
    ["Engineer III", 19],
    ["Information Systems Analyst III", 19],
    ["Information Technology Officer I", 19],
    ["Administrative Officer V", 18],
    ["Attorney II", 18],
    ["Computer Programmer III", 18],
    ["Guidance Services Specialist II", 18],
    ["Health Education and Promotion Officer III", 18],
    ["Internal Auditor III", 18],
    ["Librarian III", 18],
    ["Medical Officer II", 18],
    ["Planning Officer III", 18],
    ["Nutritionist-Dietitian III", 18],
    ["Project Development Officer III", 18],
    ["Senior Administrative Assistant V", 18],
    ["Special Investigator III", 18],
    ["Statistician III", 18],
    ["Computer Maintenance Technologist III", 17],
    ["Dentist II", 17],
    ["Information Systems Researcher III", 17],
    ["Accountant II", 16],
    ["Architect II", 16],
    ["Attorney I", 16],
    ["Engineer II", 16],
    ["Guidance Services Specialist I", 16],
    ["Information Systems Analyst II", 16],
    ["Administrative Officer IV", 15],
    ["Agriculturist II", 15],
    ["College Librarian II", 15],
    ["Computer Programmer II", 15],
    ["Creative Arts Specialist II", 15],
    ["Human Resource Management Officer II", 15],
    ["Internal Auditor II", 15],
    ["Librarian II", 15],
    ["Nurse II", 15],
    ["Nutritionist-Dietitian II", 15],
    ["Planning Officer II", 15],
    ["Project Development Officer II", 15],
    ["Publication Production Supervisor", 15],
    ["Registrar II", 15],
    ["Security Officer II", 15],
    ["Senior Administrative Assistant III", 15],
    ["Special Investigator II", 15],
    ["Statistician II", 15],
    ["Administrative Officer III", 14],
    ["Cashier II", 14],
    ["Dentist I", 14],
    ["Health Education and Promotion Officer II", 14],
    ["Records Officer II", 14],
    ["Senior Administrative Assistant II", 14],
    ["Supply Officer II", 14],
    ["College Librarian I", 13],
    ["School Librarian III", 13],
    ["Senior Administrative Assistant I", 13],
    ["Vocational Placement Coordinator I", 13],
    ["Accountant I", 12],
    ["Administrative Assistant VI", 12],
    ["Legal Assistant II", 12],
    ["School Librarian II", 12],
    ["Accounting Analyst", 11],
    ["Administrative Assistant V", 11],
    ["Administrative Officer II", 11],
    ["Agriculturist I", 11],
    ["Aquaculturist I", 11],
    ["Budget Officer I", 11],
    ["Communications Equipment Operator IV", 11],
    ["Computer Maintenance Technologist I", 11],
    ["Creative Arts Specialist I", 11],
    ["Dormitory Manager II", 11],
    ["Fiscal Examiner I", 11],
    ["Human Resource Management Officer I", 11],
    ["Internal Auditor I", 11],
    ["Librarian I", 11],
    ["Nurse I", 11],
    ["Nutritionist-Dietitian I", 11],
    ["Planning Officer I", 11],
    ["Project Development Officer I", 11],
    ["Psychologist I", 11],
    ["Registrar I", 11],
    ["School Librarian I", 11],
    ["Social Welfare Officer I", 11],
    ["Statistician I", 11],
    ["Warehouseman III", 11],
    ["Administrative Officer I", 10],
    ["Cashier I", 10],
    ["Cinematographer I", 10],
    ["Computer File Librarian II", 10],
    ["Legal Assistant I", 10],
    ["Supply Officer I", 10],
    ["Administrative Assistant III", 9],
    ["Communications Equipment Operator III", 9],
    ["Dormitory Manager I", 9],
    ["Printing Foreman", 9],
    ["Science Research Assistant", 9],
    ["Science Research Technician I", 9],
    ["Senior Bookkeeper", 9],
    ["Administrative Assistant II", 8],
    ["Aquacultural Technician II", 8],
    ["Artist-Illustrator II", 8],
    ["Bookkeeper", 8],
    ["Computer File Librarian I", 8],
    ["Disbursing Officer II", 8],
    ["Draftsman II", 8],
    ["Internal Auditing Assistant", 8],
    ["Project Development Assistant", 8],
    ["Security Guard III", 8],
    ["Administrative Assistant I", 7],
    ["Copy Reader", 7],
    ["Accounting Clerk II", 6],
    ["Administrative Aide VI", 6],
    ["Clerk III", 6],
    ["Communications Equipment Operator II", 6],
    ["Disbursing Officer I", 6],
    ["Draftsman I", 6],
    ["Electronics and Communications Equipment Technician I", 6],
    ["Laboratory Technician I", 6],
    ["Mechanic II", 6],
    ["Mechanical Plant Operator II", 6],
    ["Photoengraver II", 6],
    ["Proofreader II", 6],
    ["Typesetter II", 6],
    ["Utility Foreman", 6],
    ["Administrative Aide V", 5],
    ["Handicraft Worker II", 5],
    ["Legal Aide", 5],
    ["Master Fisherman 1", 5],
    ["Security Guard II", 5],
    ["Administrative Aide IV", 4],
    ["Clerk II", 4],
    ["Communications Equipment Operator I", 4],
    ["Dental Aide", 4],
    ["Fiscal Clerk I", 4],
    ["Heavy Equipment Operator I", 4],
    ["Houseparent I", 4],
    ["Marine Engineman I", 4],
    ["Mechanic I", 4],
    ["Mechanical Plant Operator I", 4],
    ["Metal Worker I", 4],
    ["Nursing Attendant I", 4],
    ["Statistician Aide", 4],
    ["Telegram Carrier", 4],
    ["Watchman II", 4],
    ["Administrative Aide III", 3],
    ["Clerk I", 3],
    ["Cook I", 3],
    ["Coxswain", 3],
    ["Driver I", 3],
    ["Fisherman", 3],
    ["Handicraft Worker I", 3],
    ["Lineman I", 3],
    ["Security Guard I", 3],
    ["Administrative Aide II", 2],
    ["Construction and Maintenance Man", 2],
    ["Farm Worker I", 2],
    ["Guesthouse Caretaker", 2],
    ["Light Equipment Operator", 2],
    ["Nurse Maid I", 2],
    ["Reproduction Machine Operator I", 2],
    ["Watchman I", 2],
    ["Administrative Aide I", 1],
    ["Utility Worker I", 1]
];

const vacancyPositions = [
    "Administrative Aide I",
    "Watchman I",
    "Administrative Officer I",
    "Administrative Assistant III",
    "Legal Assistant I",
    "Project Development Officer I",
    "Administrative Officer II",
    "Administrative Officer IV",
    "School Principal I",
    "Project Development Officer II",
    "Education Program Supervisor"
];

async function seed() {
    try {
        // Clear existing just in case
        await pool.query('TRUNCATE TABLE positions');

        let insertCount = 0;

        const insertPos = async (cat, pos, sg) => {
            const inVac = vacancyPositions.includes(pos) ? 1 : 0;
            await pool.query('INSERT INTO positions (category, title, salaryGrade, in_vacancy) VALUES (?, ?, ?, ?)', [cat, pos, sg.toString(), inVac]);
            insertCount++;
        };

        for (let [pos, sg] of teaching) await insertPos('Teaching', pos, sg);
        for (let [pos, sg] of schoolAdmin) await insertPos('School Administration', pos, sg);
        for (let [pos, sg] of relatedTeaching) await insertPos('Related Teaching', pos, sg);
        for (let [pos, sg] of nonTeaching) await insertPos('Non-Teaching', pos, sg);

        console.log(`Successfully seeded ${insertCount} positions into positions table.`);
    } catch (err) {
        console.error("Error seeding positions:", err);
    } finally {
        process.exit();
    }
}

seed();
